//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp1
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Building.
    /// </summary>
    // *** Start programmer edit section *** (Building CustomAttributes)

    // *** End programmer edit section *** (Building CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BuildingE", new string[] {
            "Name as \'Name\'",
            "Address as \'Address\'"})]
    [View("BuildingL", new string[] {
            "Name as \'Name\'",
            "Address as \'Address\'"})]
    public class Building : ICSSoft.STORMNET.DataObject
    {

        private string fAddress;

        private string fName;

        private IIS.MyApp1.DetailArrayOfRoom fRoom;

        // *** Start programmer edit section *** (Building CustomMembers)

        // *** End programmer edit section *** (Building CustomMembers)


        /// <summary>
        /// Address.
        /// </summary>
        // *** Start programmer edit section *** (Building.Address CustomAttributes)

        // *** End programmer edit section *** (Building.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (Building.Address Get start)

                // *** End programmer edit section *** (Building.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (Building.Address Get end)

                // *** End programmer edit section *** (Building.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Building.Address Set start)

                // *** End programmer edit section *** (Building.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Building.Address Set end)

                // *** End programmer edit section *** (Building.Address Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Building.Name CustomAttributes)

        // *** End programmer edit section *** (Building.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Building.Name Get start)

                // *** End programmer edit section *** (Building.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Building.Name Get end)

                // *** End programmer edit section *** (Building.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Building.Name Set start)

                // *** End programmer edit section *** (Building.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Building.Name Set end)

                // *** End programmer edit section *** (Building.Name Set end)
            }
        }

        /// <summary>
        /// Building.
        /// </summary>
        // *** Start programmer edit section *** (Building.Room CustomAttributes)

        // *** End programmer edit section *** (Building.Room CustomAttributes)
        public virtual IIS.MyApp1.DetailArrayOfRoom Room
        {
            get
            {
                // *** Start programmer edit section *** (Building.Room Get start)

                // *** End programmer edit section *** (Building.Room Get start)
                if ((this.fRoom == null))
                {
                    this.fRoom = new IIS.MyApp1.DetailArrayOfRoom(this);
                }
                IIS.MyApp1.DetailArrayOfRoom result = this.fRoom;
                // *** Start programmer edit section *** (Building.Room Get end)

                // *** End programmer edit section *** (Building.Room Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Building.Room Set start)

                // *** End programmer edit section *** (Building.Room Set start)
                this.fRoom = value;
                // *** Start programmer edit section *** (Building.Room Set end)

                // *** End programmer edit section *** (Building.Room Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "BuildingE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BuildingE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BuildingE", typeof(IIS.MyApp1.Building));
                }
            }

            /// <summary>
            /// "BuildingL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BuildingL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BuildingL", typeof(IIS.MyApp1.Building));
                }
            }
        }
    }
}

