//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp1
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Room.
    /// </summary>
    // *** Start programmer edit section *** (Room CustomAttributes)

    // *** End programmer edit section *** (Room CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RoomE", new string[] {
            "Number as \'Number\'"})]
    [View("RoomL", new string[] {
            "Number"})]
    public class Room : ICSSoft.STORMNET.DataObject
    {

        private int fNumber;

        private IIS.MyApp1.Building fBuilding;

        // *** Start programmer edit section *** (Room CustomMembers)

        // *** End programmer edit section *** (Room CustomMembers)


        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Room.Number CustomAttributes)

        // *** End programmer edit section *** (Room.Number CustomAttributes)
        public virtual int Number
        {
            get
            {
                // *** Start programmer edit section *** (Room.Number Get start)

                // *** End programmer edit section *** (Room.Number Get start)
                int result = this.fNumber;
                // *** Start programmer edit section *** (Room.Number Get end)

                // *** End programmer edit section *** (Room.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Number Set start)

                // *** End programmer edit section *** (Room.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Room.Number Set end)

                // *** End programmer edit section *** (Room.Number Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку IIS.MyApp1.Building.
        /// </summary>
        // *** Start programmer edit section *** (Room.Building CustomAttributes)

        // *** End programmer edit section *** (Room.Building CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Building"})]
        public virtual IIS.MyApp1.Building Building
        {
            get
            {
                // *** Start programmer edit section *** (Room.Building Get start)

                // *** End programmer edit section *** (Room.Building Get start)
                IIS.MyApp1.Building result = this.fBuilding;
                // *** Start programmer edit section *** (Room.Building Get end)

                // *** End programmer edit section *** (Room.Building Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Building Set start)

                // *** End programmer edit section *** (Room.Building Set start)
                this.fBuilding = value;
                // *** Start programmer edit section *** (Room.Building Set end)

                // *** End programmer edit section *** (Room.Building Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "RoomE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomE", typeof(IIS.MyApp1.Room));
                }
            }

            /// <summary>
            /// "RoomL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomL", typeof(IIS.MyApp1.Room));
                }
            }
        }
    }

    /// <summary>
    /// Detail array of Room.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfRoom CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfRoom CustomAttributes)
    public class DetailArrayOfRoom : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (IIS.MyApp1.DetailArrayOfRoom members)

        // *** End programmer edit section *** (IIS.MyApp1.DetailArrayOfRoom members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Room by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Room.
        /// </summary>
        public DetailArrayOfRoom(IIS.MyApp1.Building fBuilding) : 
                base(typeof(Room), ((ICSSoft.STORMNET.DataObject)(fBuilding)))
        {
        }

        public IIS.MyApp1.Room this[int index]
        {
            get
            {
                return ((IIS.MyApp1.Room)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(IIS.MyApp1.Room dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

